auditlog/audit/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('audit/', views.home, name='home'),
    path('task/', views.all_task, name='task'),
    path('task/<int:task_id>/toggle/', views.toggle_task, name='toggle_task'),
    path('add/', views.add_task, name='add'),
    path('<int:task_id>/edit/', views.edit_task, name='edit'),
    path('<int:task_id>/delete/', views.delete_task, name='delete'),
    path('register/', views.register, name='register'),
    path('log_out/', views.user_logout, name='log_out'),
    path('search/', views.search, name='search'),
]

auditlog/auditlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('audit.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

auditlog/audit/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    task = models.CharField (max_length = 100)
    completed = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.task
    
class AuditLog(models.Model):
    ACTION_CHOICES = [
        ('added', 'Added'),
        ('updated', 'Updated'),
        ('deleted', 'Deleted'),
        ('completed', 'completed'),
        ('incompleted', 'Incompleted'),
    ]

    user = models.ForeignKey(User, on_delete = models.CASCADE)
    task = models.ForeignKey(Task, on_delete = models.SET_NULL, null = True, blank = True)
    task_name = models.CharField(max_length = 100)
    action = models.CharField(max_length = 20, choices = ACTION_CHOICES)
    timestamp = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.user} {self.action} {self.task}"

auditlog/audit/forms.py
from django import forms
from .models import Task
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class TaskForm (forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task']

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

auditlog/audit/views.py
from django.shortcuts import render
from .models import Task, AuditLog
from .forms import TaskForm, UserRegistrationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth import logout

# Create your views here.
@login_required
def home(request):
    logs = AuditLog.objects.all().order_by('-timestamp')
    return render(request, 'home.html', {'logs': logs})

@login_required
def all_task(request):
    tasks = Task.objects.all()
    return render(request, 'task_manager.html', {'tasks':tasks})

@login_required
def add_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid:
            task = form.save (commit=False)
            task.user = request.user
            task.save()
            AuditLog.objects.create(
                user = request.user,
                task = task,
                task_name = task.task,
                action = 'added'
            )
            return redirect('task')
    else:
        form = TaskForm() 
    return render(request, 'add_task.html', {'form':form})

@login_required
def edit_task(request, task_id):
    task = get_object_or_404(Task, pk = task_id, user = request.user)
    if request.method == "POST":
        form = TaskForm(request.POST, instance = task)
        if form.is_valid():
            form.save()
            AuditLog.objects.create(
                user = request.user,
                task = task,
                task_name = task.task,
                action = 'updated'
            )
            return redirect('task')
    else:
        form = TaskForm(instance=task)
    return render(request, 'add_task.html', {'form':form})

@login_required
def delete_task(request, task_id):
    task = get_object_or_404(Task, pk = task_id, user = request.user)
    if request.method == "POST":
        AuditLog.objects.create(
            user = request.user,
            task = task,
            task_name = task.task,
            action = 'deleted'
        )
        task.delete()
        return redirect('task')
    return render(request, 'delete_task.html', {'task':task})


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            return redirect('task')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form':form})

def user_logout(request):
    if request.method == "POST":
        logout(request)
    return render(request, 'registration/log_out.html')

def toggle_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.completed = not task.completed
    task.save()
    AuditLog.objects.create(
        user = request.user,
        task = task,
        task_name = task.task,
        action = 'completed' if task.completed else 'incompleted'
    )
    return redirect('task')

def search(request):
    query = request.GET.get('q', '')
    tasks = Task.objects.none()

    if query:
        tasks = Task.objects.filter(task__icontains = query)

    return render(request, 'task_manager.html', {'query':query, 'tasks':tasks})

auditlog/audit/templates/add_task.html
{% extends "layout.html" %}

{% block content %}
<h2>
    {% if form.instance.pk %} Edit Task {% else %} Add Task {% endif %}

    <form method="post" class="form mt-4">
        {% csrf_token %}
        {{form}}
        <button class="btn btn-warning" type="submit">Submit</button>
        <a href="{% url 'task' %}" class="btn btn-warning">Back to Task Manager</a>
    </form>

</h2>
{% endblock %}

auditlog/audit/templates/delete_task.html
{% extends "layout.html" %}

{% block content %}
<h1>Are you sure you want to delete this task?</h1>

<form method="post">
    {% csrf_token %}
    <button class="btn btn-danger">Delete</button>
    <a class="btn btn-success" href="{% url 'task' %}">cancel</a>
</form>

{% endblock %}

auditlog/audit/templates/home.html
{% extends "layout.html" %}

{% block content %}
 
    <div class="container mt-4">
    <h1>Audit Log</h1>
    <div class="card mt-2 shadow-sm bg-dark text-white border border-secondary">
        <div class="card-body">
            <table class="table table-dark table-striped">
                <thead>
                    <tr>
                        <th>Time</th>                        
                        <th>Action</th>
                        <th>Task</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in logs %}
                    <tr>
                        <td>{{ log.timestamp|date:"H:i A, d M Y" }}</td>                        
                        <td>{{ log.get_action_display }}</td>
                        <td>
                            {{ log.task_name }}
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">No logs yet.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

auditlog/audit/templates/task_manager.html
{% extends "layout.html" %}

{% block content %}
<div class="container mt-4">
    <h1>TASK MANAGER</h1>
    <a class="btn btn-outline-primary m-2" href="{% url 'add' %}">Add a task</a>

    <div class="card mt-2 shadow-sm bg-dark text-white border border-secondary">
        <div class="card-body">

            {% if tasks %}
                {% for task in tasks %}
                    <div class="d-flex align-items-center justify-content-between py-2 border-bottom border-light">
                        <div class="form-check d-flex align-items-center">
                            <form method="post" action="{% url 'toggle_task' task.id %}">
                                {% csrf_token %}
                                <input  
                                        class="form-check-input me-2"
                                        type="checkbox"
                                        onchange="this.form.submit()"
                                        style="border: 2px solid white; background-color: transparent;"
                                        {% if task.completed %}checked{% endif %}
                                >
                            </form>
                            <label class="form-check-label">
                                {{ task.task }}
                            </label>
                        </div>

                        <div class="dropdown">
                            <button class="btn btn-sm" type="button" data-bs-toggle="dropdown">
                                ⋮
                            </button>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <li><a class="dropdown-item" href="{% url 'edit' task.id %}">Edit</a></li>
                                <li><a class="dropdown-item text-danger" href="{% url 'delete' task.id %}">Delete</a></li>
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p class="text-center text-secondary m-0">
                    {% if query %}
                        No tasks found for "{{ query }}"
                    {% else %}
                        No tasks yet. Add one.
                    {% endif %}
                </p>
            {% endif %}
        </div>
    </div>

</div>
{% endblock %}

auditlog/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Audit Logging System
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="cdn.jsdelivr.net">

    
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Audit Log</a>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'task' %}">Task Manager</a>
            </li>            
            <form method="GET" action="{% url 'search' %}" class="d-flex" role="search">
                <input 
                    class="form-control me-2" 
                    type="task" 
                    name="q"
                    placeholder="Search task..." 
                    value="{{ query }}"
                >

                <button class="btn btn-outline-success" type="submit">Search</button>

            </form>   
            <li class="nav-item">
                <form method="post" action="{% url 'log_out' %}" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="nav-link btn btn-link text-danger p-0 ">
                        Logout
                    </button>
                </form>
            </li>
       
        </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html> 

auditlog/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Tailwind</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% tailwind_css %}
</head>

<body class="bg-gray-50 text-black font-serif leading-normal tracking-normal">
<div class="container mx-auto">
    <section class="flex items-center justify-center h-screen">
        <h1 class="text-5xl">Django + Tailwind = ❤️</h1>
    </section>
</div>
</body>
</html>